# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 23:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0002_users_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='desc',
            field=models.TextField(default=''),
        ),
    ]
