# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0003_users_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Travels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('traveldate_from', models.DateField()),
                ('traveldate_to', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='fname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='email',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='users',
            name='access',
        ),
        migrations.RemoveField(
            model_name='users',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='users',
            name='lname',
        ),
        migrations.AddField(
            model_name='travels',
            name='users',
            field=models.ManyToManyField(related_name='travels', to='logreg.Users'),
        ),
    ]
