# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-29 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logreg', '0004_auto_20170929_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travels',
            name='users',
        ),
        migrations.DeleteModel(
            name='Travels',
        ),
    ]
